language: node_js

notifications:
  email: false

node_js:
  - '8'
  - '7'
  - '6'

install:
  - npm install

script:
  - npm run build
  
deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $NPM_TOKEN
  on:
    tags: true
